### PR TITLE
Navigation Version 2.0

### PR DESCRIPTION
**Pull request by Eshchock1**
I completely redid the old navigation bar. Simple dark top navigation bar with a menu button on the left side (click it to open side menu thingy to access other pages). Idk...tell me what u think....

### CODE REVIEW

**Comment by seendsouza** [comment]
Two points:
- it's not completely mobile friendly with the 2019
- the Robotics in 2381 Robotics in the middle is not clickable
Other than that, LGTM

**Comment by jeffrey-dot-li** [comment]
Ye its pre good the teams dont stack vertically depending on screen size i think also the design direction is a bit off but the css is clean

**Comment by allenapplehead** [comment]
CSS very clean very nice.

However the middle 2381 shouldn't be a link if it doesn't link to anything. Sponsors is misspelled.

**Comment by seendsouza** [comment]
@allenapplehead from a UX standpoint, users will click that to go to the homepage, so it should remain as a link.

**Comment by allenapplehead** [comment]
Also the vertical nav bar on the side's graphics is a bit sketchy (can see pixels)

**Pull request merged**
